name: Complete pipeline for DevOps

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
      
      - name: Build Docker Image
        run: |
          docker build -t arifansari10027/devops-practice:${{ env.SHORT_SHA }} .
      
      - name: Login to Dockerhub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
      - name: Push Dockerhub
        run: |
          docker push arifansari10027/devops-practice:${{ env.SHORT_SHA }}
      
      - name: Config Git Author
        run: |
          git config --global user.email "arifansari10027@gmail.com"
          git config --global user.name "arifansari10027"
      
      - name: Update Helm Chart with new image tag
        run: |
          sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" ./devops-practice-time-printer/values.yaml
          git add ./devops-practice-time-printer/values.yaml
          git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
          git push
